version: "3.9"

services:
  cms_php:
    build: ./cms_php
    working_dir: /var/www/cms_php
    volumes:
      - static-content:/var/www/cms_php/public
      - ./cms_php/storage:/var/www/cms_php/storage
      - ./docker/php-fpm/fpm-php.www.log:/var/log/fpm-php.www.log
    depends_on:
      - mysql
    expose:
      - 9000
    command: > 
      sh -c "
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan storage:link
        php-fpm
      "dock

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - static-content:/var/www/cms_php/public
      - ./cms_php/storage:/var/www/cms_php/storage
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - cms_php
    

  mysql:
    image: mysql:5.7.35
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123ezTour
    volumes:
      - ./cms_php/docker/mysql:/var/lib/mysql

  chat_node:
    build: ./chat_node
    expose:
        - 3000

volumes:
  static-content: